# Generated by Django 5.0.6 on 2025-04-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fech_trans', models.DateField()),
                ('descripcion', models.TextField()),
                ('cargo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('abono', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tipo_compra', models.CharField(default='Otros', max_length=100)),
            ],
        ),
    ]
