# Generated by Django 5.0.6 on 2025-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finantrack', '0002_transaccion_delete_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
